### ISSUE TITLE
Dynamixel Hello XL 430 "Enable_pos" function does not switch into correct mode if not multi-turn motor.

### ISSUE THREAD

**Issue by scccg** [hello-robot/stretch_body#12]
During execution of DynamixelHelloXL430.home() function for a motor configured without multiturn enabled, the motor did not respond to "motor.move_to(0)" command even though function was called.  It was very hard to figure out what was happening at first.  I fixed by adding:
```
    def enable_pos(self):
        if not self.hw_valid:
            return
        self.motor.disable_torque()
        if self.params['use_multiturn']:
            self.motor.enable_multiturn()
 +     else:
 +        self.motor.enable_pos()
  ```

**Comment by hello-binit** [comment]
Hi @scccg, thank you for reporting this issue and figuring out a fix. I'll test it out on my end and have a fix released soon.
