### ISSUE TITLE
Incorrect protocol error

### ISSUE THREAD

**Issue by aedsinger** [hello-robot/stretch_body#131]
When a hardware device has communication issues  may be misrepresented as a protocol error. Eg:

```[ERROR] [wacc]: SerialTimeoutException: /dev/hello-wacc : Write timeout
[WARNING] [wacc]:
----------------
Firmware protocol mismatch on wacc.
Protocol on board is None.
Valid protocols are: dict_keys(['p0', 'p1']).
Disabling device.
Please upgrade the firmware and/or version of Stretch Body.
```

When no data is returned on the bus this should be detected and a 'communication failure' error generated instead.

**Comment by hello-binit** [comment]
Solved with None checks, e.g.:

https://github.com/hello-robot/stretch_body/blob/289fcaebf31579ff399828c1b24b567bba65e40f/body/stretch_body/stepper.py#L1407-L1413
