### ISSUE TITLE
USB communication happening in dxl __init__ methods

### ISSUE THREAD

**Issue by hello-binit** [hello-robot/stretch_body#217]
Stretch Body shouldn't perform any USB communication until the `startup()` method is called. For the Head and EndOfArm classes (subclasses of the DynamixelXChain class), there is initial USB communication in the `__init__()` methods of those classes. For example:

https://github.com/hello-robot/stretch_body/blob/7650d8ea867873879f494a6511ba0bb4760d004f/body/stretch_body/dynamixel_X_chain.py#L28-L39

or

https://github.com/hello-robot/stretch_body/blob/7650d8ea867873879f494a6511ba0bb4760d004f/body/stretch_body/dynamixel_XL430.py#L146-L156

**Comment by hello-fazil** [comment]
This issue has been solved with the following commits https://github.com/hello-robot/stretch_body/pull/236/commits/86d79c7eb70269bd130423545b39444cd828e5e6 https://github.com/hello-robot/stretch_body/pull/236/commits/cbd074a685e405141f30ec12ee6ab90a28e204f0
