### ISSUE TITLE
WristYaw joint rotates erroneously towards the hardstops on robot exit

### ISSUE THREAD

**Issue by hello-fazil** [hello-robot/stretch_body#229]
Occasionally the WristYaw joint rotates erroneously towards the hardstops on robot exit. This seems to occur very occasionally but have observed this issue commonly when exiting the Xbox or Gamepad Teleop script.

**Comment by hello-fazil** [comment]
The root cause of this bug has not been yet identified, but from cyclic testing this issue seems to improve with the latest changes (https://github.com/hello-robot/stretch_body/pull/236) yet occurs occasionally

**Comment by aedsinger** [comment]
We haven't seen this for some time, may have been fixed inadvertently. We'll keep an eye out for it.

**Comment by hello-binit** [comment]
Closing for now. Please open a new issue if this resurfaces.
