### ISSUE TITLE
DXL startup fails when multiple threaded instances

### ISSUE THREAD

**Issue by aedsinger** [hello-robot/stretch_body#230]
The following fails:

w=wrist_yaw.WristYaw()
w.startup()
w.stop()
w=wrist_pitch.WristPitch()
w.startup()
w.stop()
time.sleep(0.5)
w = wrist_roll.WristRoll()
w.startup()
w.stop()

but this succeeds:

w=wrist_yaw.WristYaw()
w.startup(threaded=False)
w.stop()
w=wrist_pitch.WristPitch()
w.startup(threaded=False)
w.stop()
w = wrist_roll.WristRoll()
w.startup(threaded=False)
w.stop()

**Comment by hello-fazil** [comment]
Solved with the commit https://github.com/hello-robot/stretch_body/pull/236/commits/95658899be7e6367e920d99bdd6c4482e3841046
It seems like overwriting the parent `startup()` method from the WristYaw and WristRoll classes blocks the shared port_handler for each other.
