### ISSUE TITLE
NAN can cause joint to go to limit

### ISSUE THREAD

**Issue by aedsinger** [hello-robot/stretch_body#232]
From CK: 

nan value as input to move_to commands can result in motion to the extremes of a joint (e.g., lift going down into the ground). Should we check for this? 
I had been using numpy.clip to enforce joint limits prior to sending a command to stretch_body, but a nan input resulted in a nan output.
I’m explicitly checking for nans now, but it might be worth having a check in stretch_body

**Comment by hello-fazil** [comment]
This Bug is fixed by this #283
