### ISSUE TITLE
stretch_camera_streams_check.py fail

### ISSUE THREAD

**Issue by aedsinger** [hello-robot/stretch_body#239]
If I don't have a D405 installed and run the script I get:

Traceback (most recent call last):
  File "/home/hello-robot/repos/stretch_body/./tools/bin/stretch_camera_streams_check.py", line 46, in <module>
    d405_serial = connected_devices['Intel RealSense D405']
KeyError: 'Intel RealSense D405'

We should exception catch this.

**Comment by hello-fazil** [comment]
Good catch! Thank you for reporting. This should have been fixed with this commit https://github.com/hello-robot/stretch_body/commit/36994b14faa052ee5c58bac93493f3f8b84d3160
