### ISSUE TITLE
Dxl Move_to near zero velocity causes fast motion

### ISSUE THREAD

**Issue by hello-binit** [hello-robot/stretch_body#252]
With the dynamixel joints, using the `move_to()` or `move_by()` methods (and perhaps other motion methods), commanding a zero or near zero velocity causes the Dynamixel joint to move to the position goal with a very fast velocity. This is counterintuitive to the behavior I'd expect. Near zero or zero velocity should cause the joint to move slowly or not at all towards the position goal.

A minimum reproducible example:

```python
import stretch_body.robot
r = stretch_body.robot.Robot()
r.startup()

r.end_of_arm.move_to('wrist_pitch', 0.3) # motion at normal speed
r.end_of_arm.move_to('wrist_pitch', 0.0, 0.02) # causes fast motion because 0.02 rad/s is near zero
r.end_of_arm.move_to('wrist_pitch', 0.3) # motion at normal speed
r.end_of_arm.move_to('wrist_pitch', 0.0, 0.1) # causes slow motion. 0.1 rad/s is not near zero enough to cause the fast motion
```
A fix to this bug would remove the counterintuitive behavior.

**Comment by hello-fazil** [comment]
Fixed with the PR #276
