### ISSUE TITLE
Tool Dex Wrist mixing parameters/classes between Stretch Body & Stretch Tool Share

### ISSUE THREAD

**Issue by hello-binit** [hello-robot/stretch_body#261]
The classes and parameters to support a Dex Wrist were merged into Stretch Body. However, the [`tool_stretch_dex_wrist.devices`](https://github.com/hello-robot/stretch_body/blob/289fcaebf31579ff399828c1b24b567bba65e40f/body/stretch_body/robot_params_RE2V0.py#L647) parameters still point to the original code/parameters in Stretch Tool Share. This results in weird setups where code is pulled from Stretch Body, but the parameters are pulled from Stretch Tool Share, e.g. when running the `stretch_wrist_pitch_jog.py` tool.

![Screenshot from 2024-01-31 21-05-21](https://github.com/hello-robot/stretch_body/assets/64861565/e855bbdd-34ef-4724-9872-6f3bb736ada0)

To fix this, three changes are needed:
1. Parameters in Stretch Body should point to classes from Stretch Body. If functionality needs to be model or tool specific, conditional statements should be added that check the `model_name` or `robot.tool` parameters.
2. Parameters and classes in Stretch Tool Share should be updated to be identical to the ones in Stretch Body. Until we deprecate loading these tools from the tool share, it's important that they behave functionally the same.
3. Show a warning when loading the tool from the Tool Share. Write a REx_migration tool to help users migrate. In the future, we should disallow loading `tool_stretch_dex_wrist` from the Tool Share.

**Comment by aedsinger** [comment]
This is resolved in PR https://github.com/hello-robot/stretch_body/pull/273 and https://github.com/hello-robot/stretch_body/pull/272
