### ISSUE TITLE
RE1's nominal parameters missing "robot_collision_mgmt"

### ISSUE THREAD

**Issue by hello-binit** [hello-robot/stretch_body#263]
With Stretch Body 0.7.2 (latest currently released), model name `RE1V0` is missing a parameter named "robot_collision_mgmt", causing tools like stretch_robot_home.py to fail with error:
```
[ERROR] [robot_collision_mgmt]: Parameters for device robot_collision_mgmt not found. Check parameter YAML and device name. Exiting...
```

**Comment by aedsinger** [comment]
This is fixed in this PR, now merged to master:

https://github.com/hello-robot/stretch_body/pull/259
