### ISSUE TITLE
In Gamepad Gripper gradually loses grip while grasping something above a certain threshold

### ISSUE THREAD

**Issue by hello-fazil** [hello-robot/stretch_body#289]
From BM:
In gamepad teleop, the gripper doesn’t do the discrete backoff behavior, but instead slowly reduces grip force consistently above a certain threshold.
Its very noticeable with high force and wider aperture, but it also happens on significantly smaller objects than I would expect it to eg screwdriver. Might just be setting a threshold force for this, or having it timeout after a certain period of time (since the backoff behavior tends to reset the force very quickly)

**Comment by aedsinger** [comment]
Fixed here https://github.com/hello-robot/stretch_body/pull/294
