### ISSUE TITLE
`robot.wait_command()` doesn't wait until the desired motion is done

### ISSUE THREAD

**Issue by ProKil** [hello-robot/stretch_body#321]
When using `robot.base.translate_by()`, I encounter the following problem:

When I call `robot.base.translate_by(1); robot.push_command(); robot.wait_command()`, the robot stops before translating 1 meter. But if I give it enough time before or after calling `wait_command()`, then it could finish the desired motion. To reproduce see the following script:

```python
import stretch_body.robot as rb
import time


if __name__ == '__main__':
    
    robot = rb.Robot()
    robot.startup()

    print(robot.base.status['x'], robot.base.status['y'], robot.base.status['theta'])
    robot.base.translate_by(1)
    robot.push_command()
    time.sleep(10)
    robot.wait_command()
    print(robot.base.status['x'], robot.base.status['y'], robot.base.status['theta'])

    robot.stop()
```
results in the following output (indicating the correct translation):

```
[WARNING] [robot]: Not able to use asyncio for transport communications. Defaulting to sync.
-5.125146163131866e-06 0.0 0.0
0.9999646797380163 0.00824831154241202 6.361304339286278e-06
```

Moving `time.sleep(10)` after `wait_command()` will also result in correct translation:
```
[WARNING] [robot]: Not able to use asyncio for transport communications. Defaulting to sync.
-2.6518169192695066e-06 -6.32054200644383e-11 4.7669521120912184e-05
1.0002982531400872 0.005147919385949634 0.00136212435690839
```

**However**, omitting `time.sleep(10)` will result in 

```
[WARNING] [robot]: Not able to use asyncio for transport communications. Defaulting to sync.
5.367379438457905e-06 9.097739228636215e-11 3.3900115527111285e-05
0.0006981162939013875 8.79377745066634e-08 0.00036106441335873415
```
The robot is stopped before finishing the desired motion. 

Based on the above observation, I think `wait_command()` returns before the previous command is completed.

**Comment by hello-fazil** [comment]
This is issue is fixed with https://github.com/hello-robot/stretch_body/pull/341
@ProKil thankyou for raising this issue. You can update your stretch body to latest version and check if you still see the issue. Until that I am closing this issue.
