### ISSUE TITLE
OpenGL.acceleratesupport Warning

### ISSUE THREAD

**Issue by hello-binit** [hello-robot/stretch_body#323]
I'm seeing the following warning print out whenever Stretch Body is used:

```
[INFO] [OpenGL.acceleratesupport]: No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
```

**Comment by hello-fazil** [comment]
Fixed in https://github.com/hello-robot/stretch_body/pull/332/commits/c4e742aecb00477c74777150171a6b5ebeea910e
